---
version: 0.2

env:
  variables:
    KEY: "value"

phases:
  install:
    commands:
      - make install
  pre_build:
    commands:
      - make test
      - echo ${RELEASE_BUCKET_NAME}
      - echo ${ARTIFACT_NAME}
      - echo ${ARTIFACT_FILENAME}
  build:
    commands:
      - make build
  post_build:
    commands:
      - echo Post build command. Doint nothing.

artifacts:
  files:
    hello

